In [2]:
import numpy as np

In [121]:
class HMM():
    def __init__(self,A,B,pi):
        self.A=A   #状态转移概率矩阵
        self.B=B   #观测概率矩阵
        self.pi=pi  #初始概率状态向量
    
    def forward(self,obs_seq):
        '''
        前向算法
        
        输入观测序列obs_seq，输出前向概率矩阵alpha
            alpha:维度T*N
                T -- 观测序列长度
                N -- 所有可能的状态数
        '''
        T=len(obs_seq)
        
        alpha=[]
        alpha.append(self.pi*self.B[:,obs_seq[0]])
        
        for t in range(1,T):
            alpha.append((np.dot(alpha[t-1],self.A)*self.B[:,obs_seq[t]]).reshape(1,-1).tolist()[0])
        alpha=np.array(alpha)
        return alpha
    
    def backward(self,obs_seq):
        '''
        后向算法
        
        输入观测序列obs_seq，输出后向概率矩阵beta
            beta:维度T*N
                T -- 观测序列长度
                N -- 所有可能的状态数
        '''
        T=len(obs_seq)
        N=self.A.shape[0]
        
        beta=[]
        beta.append([1 for _ in range(N)])
        
        for t in range(T-1)[::-1]:
            beta.append(np.dot(self.A,self.B[:,obs_seq[t+1]]*beta[-1]).reshape(1,-1).tolist()[0])
        beta=np.array(beta)[::-1]
        return beta
    
    def predict(self,obs_seq):
        '''
        用维特比算法实现隐马尔可夫模型的预测
        
        输入模型(A,B,pi)和观测序列obs_seq，输出最优路径I及其概率
            delte:维度T*N
                T -- 观测序列长度
                N -- 所有可能的状态数
                delte[t-1][i] -- 在时刻t状态为i的所有单个路径中概率最大值
            psi:维度T*N
                psi[t-1][i] -- 在时刻t状态为i的所有单个路径中概率最大的路径的第t-i个节点
        '''
        T=len(obs_seq)
        N=self.A.shape[0]
        
        #初始化
        delte,psi=[],[]
        I=[]
        delte.append((self.pi*self.B[:,obs_seq[0]]).reshape(1,-1).tolist()[0])
        psi.append([-1 for _ in range(N)])
        
        #递推
        for t in range(1,T):
            delte.append((np.amax((delte[-1]*self.A.T).T,axis=0)*self.B[:,obs_seq[t]]).reshape(1,-1).tolist()[0])
            psi.append(np.argmax((delte[-2]*self.A.T).T,axis=0).reshape(1,-1).tolist()[0])
        
        #终止
        P=max(delte[-1])
        I.append(np.argmax(delte[-1]))

        #最优路径回溯
        for t in range(T-1)[::-1]:
            I.append(psi[t+1][I[-1]])
        I=I[::-1]
        return I,P
    def fit(self,seqs):
        '''
        
        '''
        if len(np.shape(seqs))<2 or len(np.shape(seqs))>3:
            print("输入错误！")
            return
        T=len(obs_seq)
        
        if sta_seq!=[]:
            sta_trans_dict={}
            for t in range(T-1):
                sta_trans_dict[(sta_seq[t],sta_seq[t+1])]=sta_trans_dict.get((sta_seq[t],sta_seq[t+1]),0)+1
            for 

In [124]:
### 统计学习方法例10.2
A=np.array([[0.5,0.2,0.3],[0.3,0.5,0.2],[0.2,0.3,0.5]])
B=np.array([[0.5,0.5],[0.4,0.6],[0.7,0.3]])
pi=np.array([0.2,0.4,0.4])
h = HMM(A,B,pi)

obs_seq=[0,1,0]
alpha = h.forward(obs_seq)
print("forward alpha:",alpha)
print ("forward: P(O|lambda) = %f" %sum(alpha[-1,:]))
beta = h.backward(obs_seq)
print("backward beta",beta)
print ("backward: P(O|lambda) = %f" %sum(beta[0,:]*pi*B[:,0]))

### 统计学习方法例10.3
path,p=h.predict([0,1,0])
print("最优路径概率",p)
print("最优路径",path)

forward alpha: [[0.1      0.16     0.28    ]
 [0.077    0.1104   0.0606  ]
 [0.04187  0.035512 0.052836]]
forward: P(O|lambda) = 0.130218
backward beta [[0.2451 0.2622 0.2277]
 [0.54   0.49   0.57  ]
 [1.     1.     1.    ]]
backward: P(O|lambda) = 0.130218
最优路径概率 0.014699999999999998
最优路径 [2, 2, 2]


In [123]:
### 网上查找的海藻数据
observations = ('dry','dryish','damp','soggy')   #观测集合
states = ('sunny','cloudy','rainy')              #状态集合

start_probability ={'sunny':0.6,'cloudy':0.2,'rainy':0.2}

transition_probability = {
    'sunny':{'sunny':0.5,'cloudy':0.375,'rainy':0.125},
    'cloudy':{'sunny':0.25,'cloudy':0.125,'rainy':0.625},
    'rainy':{'sunny':0.25,'cloudy':0.375,'rainy':0.375}
}

emission_probability ={
    'sunny':{'dry':0.6,'dryish':0.2,'damp':0.15,'soggy':0.05},
    'cloudy':{'dry':0.25,'dryish':0.25,'damp':0.25,'soggy':0.25},
    'rainy':{'dry':0.05,'dryish':0.1,'damp':0.35,'soggy':0.50}
}

### 将数据转换为
def gengerate_index_map(labels):
    '''
    建立索引表'''
    index_label = {}
    label_index = {}

    i =0
    for l in labels:
        index_label[i] =l
        label_index[l] =i

        i+=1
    return label_index,index_label
states_label_index,states_index_label = gengerate_index_map(states)
observations_label_index,observations_index_label = gengerate_index_map(observations)

def convert_observations_to_index(observations,label_index):
    list =[]
    for o in observations:
        list.append(label_index[o])
    return list

def convert_map_to_matrix(map,label_index1,label_index2):
    '''
    建立概率矩阵'''
    m = np.empty((len(label_index1),len(label_index2)),dtype = float)
    for line in map:
        for col in map[line]:
            m[label_index1[line]][label_index2[col]] = map[line][col]
    return m

def convert_map_to_vector(map,label_index):
    '''
    建立概率向量'''
    v = np.empty(len(map),dtype = float)
    for e in map:
        v[label_index[e]] =map[e]
    return v

A = convert_map_to_matrix(transition_probability,states_label_index,states_label_index)
print ('状态转移概率矩阵:',A)
B = convert_map_to_matrix(emission_probability,states_label_index,observations_label_index)
print ('观测概率矩阵:',B)
observations_index = convert_observations_to_index(observations,observations_label_index)
print ('观测序列索引:',observations_index)
pi = convert_map_to_vector(start_probability,states_label_index)
print ('初始概率状态向量:',pi)

h = HMM(A,B,pi)
# 人为定义的海藻状态序列
obs_seq = ('dry','damp','soggy')
obs_seq_index = convert_observations_to_index(obs_seq,observations_label_index)

# 计算P(o|lambda)
alpha = h.forward(obs_seq_index)
print(alpha)
print ("forward: P(O|lambda) = %f" %sum(alpha[-1,:]))
beta = h.backward(obs_seq_index)
print(beta)
print ("backward: P(O|lambda) = %f" %sum(beta[0,:]*pi*B[:,0]))

# 预测
ss,p = h.predict(obs_seq_index)
path = []
for s in ss:
    path.append(states_index_label[s])

print("最有可能的隐藏序列为：" ,path)
print("viterbi: P(I|O) =%f"% p)

状态转移概率矩阵: [[0.5   0.375 0.125]
 [0.25  0.125 0.625]
 [0.25  0.375 0.375]]
观测概率矩阵: [[0.6  0.2  0.15 0.05]
 [0.25 0.25 0.25 0.25]
 [0.05 0.1  0.35 0.5 ]]
观测序列索引: [0, 1, 2, 3]
初始概率状态向量: [0.6 0.2 0.2]
[[0.36       0.05       0.01      ]
 [0.02925    0.03625    0.028     ]
 [0.00153438 0.0065     0.01840625]]
forward: P(O|lambda) = 0.026441
[[0.05984375 0.0821875  0.07875   ]
 [0.18125    0.35625    0.29375   ]
 [1.         1.         1.        ]]
backward: P(O|lambda) = 0.026441
最有可能的隐藏序列为： ['sunny', 'cloudy', 'rainy']
viterbi: P(I|O) =0.010547
